% ============================================================
% Author: Tsiridis Theodoros
% Year: 2026
%
% Diploma Thesis:
% Covariance Models in Point Adjustment Applications
% for the Analysis of Gravity Field Components
%
% Aristotle University of Thessaloniki (AUTH)
% Department of Surveying and Geodesy Engineering
%
% ------------------------------------------------------------
% Copyright (c) 2026 Tsiridis T.
% All rights reserved.
%
% This code is provided for academic purposes only.
% ============================================================


function plot_empirical_covariance(results)
%PLOT_EMPIRICAL_COVARIANCE Plot empirical covariance function.

lags_all   = results.lags;
C_all      = results.C_emp;
lags_valid = results.lags_valid;
C_valid    = results.C_emp_valid;
C0_emp     = results.C0_emp;
Lhalf_emp  = results.Lhalf_emp;
min_pairs  = results.min_pairs_bin;

figure('Color','w');
hold on;
grid on;
box on;

h1 = plot(lags_all, C_all, '-o', ...
    'LineWidth', 1.0, ...
    'MarkerSize', 4);

h2 = plot(lags_valid, C_valid, 'o', ...
    'LineWidth', 1.5, ...
    'MarkerSize', 5);

target_emp = 0.5 * C0_emp;
h3 = yline(target_emp, '--', '$0.5\,C(0)$', ...
    'Interpreter','latex', ...
    'LabelHorizontalAlignment','left');

xlabel('Lag distance $h$ (km)', 'Interpreter','latex');
ylabel('Empirical covariance $C(h)$ (mGal$^2$)', 'Interpreter','latex');
title('Empirical covariance function', 'Interpreter','latex');

if isfinite(Lhalf_emp)
    h4 = xline(Lhalf_emp, '--', ...
        sprintf('$\\xi_{1/2}^{(emp)} \\approx %.2f\\ \\mathrm{km}$', Lhalf_emp), ...
        'Interpreter','latex', ...
        'LabelOrientation','horizontal', ...
        'LabelVerticalAlignment','bottom', ...
        'LabelHorizontalAlignment','left');

    legend([h1 h2 h3 h4], { ...
        'Empirical covariance', ...
        sprintf('Valid bins ($N_{pairs} \\geq %d$)', min_pairs), ...
        '$0.5\,C(0)$', ...
        '$\xi_{1/2}^{(emp)}$'}, ...
        'Interpreter','latex', ...
        'Location','northeast');
else
    legend([h1 h2 h3], { ...
        'Empirical covariance', ...
        sprintf('Valid bins ($N_{pairs} \\geq %d$)', min_pairs), ...
        '$0.5\,C(0)$'}, ...
        'Interpreter','latex', ...
        'Location','northeast');
end

xl = xlim;
yl = ylim;

if isfinite(Lhalf_emp)
    txt = { ...
        sprintf('Empirical $C(0)$: %.2f $\\mathrm{mGal}^2$', C0_emp), ...
        sprintf('Empirical $\\xi_{1/2}$: %.2f km', Lhalf_emp), ...
        sprintf('Minimum pairs/bin: %d', min_pairs) ...
        };
else
    txt = { ...
        sprintf('Empirical $C(0)$: %.2f $\\mathrm{mGal}^2$', C0_emp), ...
        'Empirical $\xi_{1/2}$: not available', ...
        sprintf('Minimum pairs/bin: %d', min_pairs) ...
        };
end

text(xl(1) + 0.02*(xl(2)-xl(1)), ...
    yl(1) + 0.98*(yl(2)-yl(1)), ...
    txt, ...
    'VerticalAlignment','top', ...
    'Interpreter','latex', ...
    'BackgroundColor','w');

hold off;
end